name: Run Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit, mobile]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        playwright install

    - name: Install system dependencies for all browsers
      run: npx playwright install-deps

    - name: Run tests on ${{ matrix.browser }}
      run: |
        if [ "${{ matrix.browser }}" = "mobile" ]; then
          pytest --device="iPhone 13" --alluredir=allure-results
        else
          pytest --browser=${{ matrix.browser }} --alluredir=allure-results
        fi
