name: Run Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright and browsers
      run: |
        pip install playwright
        playwright install

    - name: Install system dependencies for all browsers (Chromium, Firefox, WebKit)
      run: |
        npx playwright install-deps

    - name: Run Pytest with WebKit and Allure
      run: |
        pytest --browser=webkit --alluredir=allure-results
